package com.blueice.mapper;

import com.blueice.model.SysRolePrivilege;
import java.util.List;

public interface SysRolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    int insert(SysRolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_privilege
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    List<SysRolePrivilege> selectAll();
}