package com.blueice.mapper;

import com.blueice.model.SysUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    SysUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    int updateByPrimaryKey(SysUser record);

    //调用存储过程,根据id查询用户.
    void selectUserById(SysUser user);

    //调用存储过程.根据用户名模糊查询，并分页.
    List<SysUser> selectUserPage(Map<String, Object> params);

    //调用存储过程.添加用户，并设置角色.
    int insertUserAndRole(@Param("user")SysUser user, @Param("roleIds")String roleIds);

}