package com.blueice.mapper;

import com.blueice.model.UserInfo;
import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Wed Oct 24 18:08:38 CST 2018
     */
    List<UserInfo> selectAll();
}