package com.blueice.mapper;

import com.blueice.model.UserInfo;
import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user info
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    List<UserInfo> selectAll();
}