#指定端口
server:
 port: 8080

# 此名称会在服务注册中心显示 。
spring:
 application:
  name: report-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000