#指定端口
server:
  port: 8080

# 此名称会在服务注册中心显示 。
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    city:
      path: /city/**
      serviceId: city-server
    date:
      path: /data/**
      serviceId: data-server