package com.blueice.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sys_role_privilege
 */
public class SysRolePrivilege {
    /**
     * Database Column Remarks:
     *   角色ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.role_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    private Long roleId;

    /**
     * Database Column Remarks:
     *   权限ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.privilege_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    private Long privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.role_id
     *
     * @return the value of sys_role_privilege.role_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.role_id
     *
     * @param roleId the value for sys_role_privilege.role_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.privilege_id
     *
     * @return the value of sys_role_privilege.privilege_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.privilege_id
     *
     * @param privilegeId the value for sys_role_privilege.privilege_id
     *
     * @mbg.generated Mon Dec 24 17:59:27 CST 2018
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}