#指定服务端口
server:
 port: 8080



spring:
 application:
  name: microservice-consumer-movie # 此名称会在服务注册中心显示 。

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

loggin:
  level:
    root: INFO
    com.blueice: DEBUG


#在配置文件中设置Ribbon
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule